channels: 
  - conda-forge
dependencies:
  - python=3.9
  - pip=24.0
  - pip:
    - python-dotenv
    - azure-ai-ml
    - azure-identity
    - promptflow
    - promptflow-tools
    - keyrings.alt
    - numpy
    - pandas
    - ipykernel