$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: insurance_training_pipeline
jobs:
  data_engineering:
    type: spark
    code: ./src
    entry:
      file: spark_feature_eng.py
    conf:
      spark.driver.cores: 4
      spark.driver.memory: 16g
      spark.executor.cores: 4
      spark.executor.memory: 16g
      spark.executor.instances: 24

    inputs:
      raw_data:
        type: uri_file
        path: abfss://insurance-claims@vinceprojectdata.dfs.core.windows.net/policies.pq
        mode: direct

    outputs:
      training_data:
        type: uri_file
        path: abfss://insurance-claims@vinceprojectdata.dfs.core.windows.net/training_data
        mode: direct

    args: >-
      --raw_data ${{inputs.raw_data}}
      --training_data ${{outputs.training_data}}
    identity:
      type: user_identity

    resources:
      instance_type: standard_e16s_v3
      runtime_version: "3.3"
  
  

    



  