# out-of-box-monitoring.yaml
$schema:  http://azureml/sdk-2-0/Schedule.json
name: claims_model_monitoring
display_name: Insurance Claims Model Monitoring
description: Monitor the Insurance Claims model for drift and data quality issues

trigger:
  # perform model monitoring activity daily at 3:15am
  type: recurrence
  frequency: day #can be minute, hour, day, week, month
  interval: 1 # #every day
  schedule: 
    hours: 3 # at 3am
    minutes: 15 # at 15 mins after 3am

create_monitor:

  compute: # specify a spark compute for monitoring job
    instance_type: standard_e4s_v3
    runtime_version: "3.3"

  monitoring_target: 
    ml_task: classification # model task type: [classification, regression, question_answering]
    endpoint_deployment_id: azureml:claims-vh:claims-classif-main # azureml endpoint deployment id

  alert_notification: # emails to get alerts
    emails:
      - vhoudebine@microsoft.com
      