id: bring_your_own_data_qna
name: Bring Your Own Data QnA
environment:
  python_requirements_txt: requirements.txt
inputs:
  question:
    type: string
    default: Does my boat owners policy cover racing in contests?
    is_chat_input: false
outputs:
  output:
    type: string
    reference: ${answer_the_question_with_context.output}
nodes:
- name: lookup
  type: python
  source:
    type: package
    tool: promptflow_vectordb.tool.common_index_lookup.search
  inputs:
    mlindex_content: >
      embeddings:
        api_base: https://victor-aoai.openai.azure.com/
        api_type: azure
        api_version: 2023-07-01-preview
        batch_size: '16'
        connection:
          id: 
            /subscriptions/9a729243-1221-42c5-824c-9e44cb2da98d/resourceGroups/insure-rg/providers/Microsoft.MachineLearningServices/workspaces/insure-aml/connections/aoai-connect
        connection_type: workspace_connection
        deployment: victor-ada2
        dimension: 1536
        file_format_version: '2'
        kind: open_ai
        model: text-embedding-ada-002
        schema_version: '2'
      index:
        api_version: 2023-07-01-preview
        connection:
          id: 
            /subscriptions/9a729243-1221-42c5-824c-9e44cb2da98d/resourceGroups/insure-rg/providers/Microsoft.MachineLearningServices/workspaces/insure-aml/connections/aisearch-pf-connect
        connection_type: workspace_connection
        endpoint: https://insure-ai-search.search.windows.net
        engine: azure-sdk
        field_mapping:
          content: content
          embedding: contentVector
          filename: filepath
          metadata: meta_json_string
          title: title
          url: url
        index: insure-vector-index
        kind: acs
        semantic_configuration_name: azureml-default
      self:
        path: 
          azureml://subscriptions/9a729243-1221-42c5-824c-9e44cb2da98d/resourcegroups/insure-rg/workspaces/insure-aml/datastores/workspaceblobstore/paths/azureml/87adedd5-d858-44b3-829d-218e04bd20f0/index/
        asset_id: 
          azureml://locations/eastus/workspaces/efd5a12b-772d-44b0-9e86-5c56e4ae37ea/data/insure-vector-index/versions/1
    queries: ${inputs.question}
    query_type: Hybrid (vector + keyword)
    top_k: 2
  use_variants: false
- name: generate_prompt_context
  type: python
  source:
    type: code
    path: generate_prompt_context.py
  inputs:
    search_result: ${lookup.output}
  use_variants: false
- name: Prompt_variants
  type: prompt
  source:
    type: code
    path: Prompt_variants.jinja2
  inputs:
    contexts: ${generate_prompt_context.output}
    question: ${inputs.question}
  use_variants: false
- name: answer_the_question_with_context
  type: llm
  source:
    type: code
    path: answer_the_question_with_context.jinja2
  inputs:
    deployment_name: victor-gpt35t
    temperature: 0
    top_p: 1
    max_tokens: 1000
    response_format:
      type: text
    presence_penalty: 0
    frequency_penalty: 0
    prompt_text: ${Prompt_variants.output}
  connection: aoai-connection
  api: chat
  use_variants: false
